name: Laravel Cron Job

on:
  schedule:
    - cron: '*/10 * * * *'  # S'exécute toutes les 10 minutes pour garder Render éveillé
  workflow_dispatch:        # <--- CETTE LIGNE PERMET LE LANCEMENT MANUEL

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render and Run Cron
        run: |
          curl -I -s https://cmc-6btn.onrender.com/login
          # Si vous créez la route secrète plus tard, ajoutez-la ici :
          # curl -s https://cmc-6btn.onrender.com/secretway'
